### PR TITLE
Onwards to c++11

### PR DESCRIPTION
**Pull request by mgbellemare**
This makes the minimum changes to the ALE to make it compile with C++11 features. The continuous integration build is passing, which gives me some reassurance that this will mostly work. @mcmachado @mhauskn @alcinos please compile this PR on your machines and let me know if something needs addressing.

### CODE REVIEW

**Comment by mgbellemare** [comment]
There is also the related question of whether this should be brought into the dev branch first, and further modifications made there.

**Comment by mcmachado** [comment]
@mgbellemare I just downloaded and compiled this PR. Aside from CMake importing the wrong SDL library, which always happens to me, everything worked fine. I compiled with and without SDL. I compiled my research code linking with the new ALE and everything also worked fine. Again, I tested with and without screen display.

I didn't test RL-Glue because I don't have any code which I can use, but I'm ok with you merging this PR.

**Comment by mcmachado** [comment]
Oh! And regarding the dev branch, I think it is probably best to merge this PR to it first. We ensure we'll have more time to test since we will be forced to use c++11 in all the other PRs we are working on.

**Comment by mgbellemare** [comment]
Okay, merging this into the dev branch.

**Pull request closed without merging**
