### PR TITLE
Allow setting ram

### PR DESCRIPTION
**Pull request by nhynes**
Being able to probe the registers would be useful, too, but this is a start.

### CODE REVIEW

**Comment by mcmachado** [comment]
@nhynes , it is not clear to me, what is the use case for this feature?

**Comment by nhynes** [comment]
It's useful when creating custom scenarios. Here's an [example](https://gist.github.com/nhynes/90fd0f2646fb1a297324e2378f25fcda) of a function that works for Pong.

**Comment by mgbellemare** [comment]
Hi @nhynes , thanks for the PR -- a little busy right now but will get back to you soon as I can get a chance.

**Comment by JesseFarebro** [comment]
Thanks for your contribution @nhynes. I'm closing this in favour of #377.

**Pull request closed without merging**
