### PR TITLE
[games] Several new games

### PR DESCRIPTION
**Pull request by tkoeppe**
Your careful review would be greatly appreciated.

### CODE REVIEW

**Comment by JesseFarebro** [comment]
@tkoeppe Can you run Backgammon? It hangs up for me, I haven't investigated much beyond this.

**Comment by tkoeppe** [comment]
@JesseFarebro: I believe we've tried all the game modes that the support code advertises. Backgammon only appears to have one valid difficulty, which is "3"; did you set that?

**Comment by JesseFarebro** [comment]
The code block linked [here](
https://github.com/tkoeppe/Arcade-Learning-Environment/blob/e6776698d22c6e866c385cf70e0a5ac6939521e1/src/games/supported/Backgammon.cpp#L87-L102) ends up in an infinite loop. Specifically, `char address = 0x81;` will be negative because it's signed (`0x81 (129) > 127`), thus `address` can never be `> 0x8d (141)` (which is interpreted as the integer value) so the loop never ends. `address` will continue to loop over `[-127, 127]` never surpassing `141` thus never terminating. Same thing for the second loop. Any idea what might have happened here?

**Comment by tkoeppe** [comment]
Ah -- our chars are unsigned, so this may be a programming error and we should really use `unsigned char` there!

**Comment by tkoeppe** [comment]
#335 should fix this. Thanks for reporting!

**Pull request merged**
