### PR TITLE
Updated @mcmachado's PR on mode settings

### PR DESCRIPTION
**Pull request by nczempin**
I've just taken the changes from https://github.com/mgbellemare/Arcade-Learning-Environment/pull/115 and removed the conflicts.

Many of the review comments still haven't been resolved.

Also, I did not try to properly merge the manuals doc/manual/manual.pdf and doc/manual/manual.tex (I'm assuming the former is produced by the latter).

To get this PR even to compile, I had to make a quick change so I wouldn't need to manually go through all the newer ROMs (those that were added after PR #115). I'm hoping that my change allows for an adequate default behaviour (falling back to the original mode), but I haven't thoroughly tested this.

**This PR is most likely not yet ready for merging, but it may be in a better state than #115.**

### CODE REVIEW

**Comment by mgbellemare** [comment]
Hi @nczempin , thanks for all the hard work! This will take me a little while to process, but I'll try to get to it quickly.

**Comment by nczempin** [comment]
This particular one didn't involve much work, just fixing and in some cases
ignoring some conflicts (as mentioned, you should definitely check the
manual) and crossing my fingers that the defaults on the new games will
work.

Also keep in mind that many of your original review comments have not yet
been addressed, with the 0x80 being just one that is easy to fix; not sure
about the others.

**Comment by mgbellemare** [comment]
Can you update me a little on where you're at with this? My understanding is you've taken the original PR and started addressing the open issues then. If that's right, let me know when it's ready for me to take a look at, and I'll give it some priority. I'll sort out the manual end of things.

**Comment by nczempin** [comment]
My status was that I'd got it working with no conflicts (modulo the manual
issue) but that there were still quite a few issues in the original PR that
I felt unprepared to handle, e. g. some open questions to you or @mcmachado.

The whole PRs plus reviews situation is very unwieldy on this one; I'll try
and provide a "wieldier" overview when I get around to it.

**Comment by nczempin** [comment]
TBH I feel that this whole thing should be done from scratch in a safer / more modular way, using most of the ideas in the original PR, but in a way that makes in possible to add the changes a step at a time without breaking things.

So the first step should be to provide the new optional interface but keep the old behaviour the same, i. e. all the ROMs report that they support only the default settings.

Then one of the games that works well with new settings, perhaps one that will benefit particularly from adding the settings, can be added.

And once that is working well, the other games can be added, starting with the ones that did not have @mgbellemare's review comments (i. e. those that did not need further discussion).

Then the remaining ones can be discussed individually, but they won't block the inclusion of all the rest.

**Comment by mgbellemare** [comment]
Yes, I think you're right. At this point you probably are most comfortable with this code (part of the issue is the original programmer -- not @mcmachado -- isn't actively involved in this project). It seems like the first step is to commit the supporting code plus one simple game. Do you want to start a fresh PR with just that? If the PRs are small I can review them reasonably quickly (< 2 days).

**Comment by nczempin** [comment]
ok, I'll do that. any preference on which game?

**Comment by mgbellemare** [comment]
No preference beyond something that's already implemented. Whichever is your favorite :)

**Comment by nczempin** [comment]
ok

**Comment by nczempin** [comment]
should I branch off dev or off master?

**Comment by mgbellemare** [comment]
Dev.

**Comment by mgbellemare** [comment]
Also, I believe the PR was halted in part because we were debating moving to C++11. Feel free to use C++11 now if necessary, we'll make it part of the new release.

**Comment by pierrelux** [comment]
What's the state of this PR ? Should it be discarded and redone from scratch ? Is C++11 still debated ? Has this feature been tested ?

**Comment by mgbellemare** [comment]
@nczempin Last time we discussed you were going to implement a basic version of this PR, with just one game supported. How far along are you? I have an hour today to work on this, and I'd like to make it a priority -- this must get wrapped up before end of August.

**Comment by nczempin** [comment]
Hm, I think I made a private branch and started on it; I'll have a look
where I've got this and will push it to my fork.

**Comment by mgbellemare** [comment]
@nczempin , did you have a chance to look at this?

**Comment by nczempin** [comment]
Sorry, I had a look and I think the changes I made were so minor that I didn't even commit them before moving to something else.

**Comment by mcmachado** [comment]
@nczempin: I don't know how closely you've been following the PRs in the ALE but I just concluded the implementation of the mode and difficulty switch in the ALE through PRs #217 #215 #214 #212 #211 #210.

Because of that, I'm closing this PR. Thank you very much!

**Pull request closed without merging**
