### PR TITLE
Array flattening

### PR DESCRIPTION
**Pull request by pedronahum**
Hi,

Just wanted to make sure all compiler warnings created by the flattening were addressed. As discussed in https://github.com/mgbellemare/Arcade-Learning-Environment/issues/224, flattening these arrays may increase the performance of ALE. 

Let me know if you would like me to check or test something. 

Regards,

### CODE REVIEW

**Comment by mgbellemare** [comment]
Hi,

I've tested out your optimization on two different MacBook Pro's, but I'm finding no change in speed. Is it possible that you're compiling without optimizations? This is something I would expect the compiler to take care of.

**Comment by pedronahum** [comment]
Hi, 

I noticed the same when using gcc (4.8 and 6.4). Maybe is something very specific for the Intel compiler.  Will take a closer look and get back to you.

**Comment by pedronahum** [comment]
To have the same "benchmark", what compiler are you using? I have a Mac that I can use for this as well.

**Comment by mgbellemare** [comment]
This is with Apple LLVM 8.1 (i.e. clang).

**Comment by pedronahum** [comment]
Thanks! I will profile then with TAU, which recently added supoort for Clang/LLVM, and let you know what I find.

**Comment by pedronahum** [comment]
Hi,

I moved my development environment to a Mac, and I have to say I am seeing exactly the same as you. I have tested with icc 18.0.1, clang LLVM version 9.0 and pgi 17.10 and in the 3 compilers, both flattening and memory alignment didn't add any performance increase. I think we can close this pull request, as I don't think it is adding much value, in fact, the opposite, I wasted some hours of your time. Apologies for this. 

In any case, now I have a proper benchmark (i.e., not Windows with icc), and if I find some ways to vectorise some of important loops I will let you know.

**Comment by mgbellemare** [comment]
No problem, thanks for looking into this! You might want to have a look at

https://github.com/deepmind/xitari

There are some optimizations in there that might be worth porting to ALE.

**Pull request closed without merging**
