### PR TITLE
Ported pacman, surround, videochess from xitari

### PR DESCRIPTION
**Pull request by weepingwillowben**
Moved over Pacman, Surround, VideoChess from xitari. 

Addresses issues #172 #319 

Tested by running the following code on the 3 environments and seeing if the results were as expected. 

```
import os
from ale_py import ALEInterface
import time
from PIL import Image
import random


def test_load_rom():
    ale = ALEInterface()
    rom = os.path.join(os.path.dirname(__file__), "fixtures/pacman.bin")
    ale.loadROM(rom)
    action_set = list(ale.getMinimalActionSet())
    for x in range(1000):
        randint = random.choice(action_set)
        res = ale.act(randint)
        obj_data = ale.getScreenRGB()
        img = Image.fromarray(obj_data)
        img.save("imgs/" + str(x) + ".jpg")


test_load_rom()
```

### CODE REVIEW

**Comment by tkoeppe** [comment]
@mgbellemare: we also have ports of these games from xitari, maybe worth aligning those efforts?

**Comment by mgbellemare** [comment]
@tkoeppe Agreed. I'll email you.

**Comment by mgbellemare** [comment]
Thanks for this! As pointed out by @tkoeppe , we may hold off on this PR as more games will be coming live from him.

**Comment by weepingwillowben** [comment]
In light of the new PR, I'll close this.

**Comment by tkoeppe** [comment]
Thanks! Did you spot any major discrepancies between our code for those three games?

**Pull request closed without merging**
