### PR TITLE
Initial travis (continuous integration) configuration file

### PR DESCRIPTION
**Pull request by jleni**
I thought it would be useful to enable CI. It is still not using SDL but it is a good start anyway.

You enable travis-ci by signing in here:
https://travis-ci.org/auth with your GitHub account and accepting the GitHub access permissions confirmation.

You can find more information here:
http://docs.travis-ci.com/user/getting-started/

### CODE REVIEW

**Comment by mhauskn** [comment]
Thanks for the PR. This looks cool, I'm in favor of merging. :+1:

**Comment by mgbellemare** [comment]
This looks really cool. However, I'd like to hold off a bit on the CI until version 0.5 is settled. Let's revisit the question in a few months?

**Comment by jleni** [comment]
Sorry, I made a mistake and deleted the PR.
I will create an issue so we can revisit continuous integration in the future

**Comment by mgbellemare** [comment]
Good idea. I think it will be a necessity not too long from now.

**Pull request closed without merging**
