### PR TITLE
SwapPort Fix

### PR DESCRIPTION
**Pull request by JesseFarebro**
@tkoeppe is there any reason that the default value of `sp` was `NO`? The sp check in `OSystem` for swap port looks like:

https://github.com/mgbellemare/Arcade-Learning-Environment/blob/186abae7f10826f4b223f825b560ad05fc7dd32d/src/emucore/OSystem.cxx#L582-L583

This would mean that the ports were always being swapped and this impacted games such as Wizard of Wor in #346.

### CODE REVIEW

**Comment by tkoeppe** [comment]
@kieranhj: I think this is your code, could you perhaps review this?

**Comment by JesseFarebro** [comment]
@kieranhj any update on this?

**Comment by kieranhj** [comment]
Apologies, the alert for this mention went into the spam folder of my personal email.

The default to "NO" was because of this line: https://github.com/mgbellemare/Arcade-Learning-Environment/blob/master/src/emucore/Console.cxx#L85

But it looks like I misinterpreted its use? A setting has to be explicitly added to the list for it to be configurable later on by the ROM Settings, so needs a default value. I'll need to go back and check whether Surround still works with the new default of "".

**Comment by justinkterry** [comment]
@kieranhj did you get a chance to check out surround?

**Comment by JesseFarebro** [comment]
The problem is as follows:

Games such as Wizar of Wor need to swap their ports. This is done via `stella.pro` and then we generate `DefProps.hxx`.
By changing the default value of the swap port we override the ROM specified value of swap port defined in `stella.pro`, hence why any game that requires a swap port wasn't working.

It seems Surround is the only game that performs a swap port outside of stella.pro. I think the proper way to solve this is to manually set `"Console.SwapPorts" "YES"` on the two known Surround ROMs in our stella.pro file. We would then need to regenerate `DefProps.hxx` and it should work as expected without messing with the default value of swap port.

**Comment by JesseFarebro** [comment]
This PR now removes manual swap port modification performed by Surround. This, in turn, allows us to remove the default swap port value in `Settings.hxx`.

I also modified `stella.pro` to enable SwapPort for all known Surround ROMs in our database. I then regenerated `DefProps.hxx` so these changes are picked up.

@tkoeppe @kieranhj could you take a look now?

I verified that Surround and other SwapPort ROMs do indeed perform a SwapPort as expected.

**Comment by kieranhj** [comment]
Thanks Jesse. This seems like a much more sensible and elegant solution to the SwapPorts problem for Surround than overriding in code.

**Comment by tkoeppe** [comment]
Thanks everyone, that's great! @mgbellemare: This seems to be a big improvement and we'd be hapy to have it committed.

**Comment by mgbellemare** [comment]
Sg, thanks @JesseFarebro !

**Pull request merged**
