### PR TITLE
Updated cmake lists to build sharedLibraryInterfaceExample. Also fixed O...

### PR DESCRIPTION
**Pull request by mhauskn**
...SX-SDL issues in sharedLibraryInterfaceExample.

### CODE REVIEW

**Comment by mhauskn** [comment]
Currently the Makefile.sharedlibrary is broken for mac. Also, to be complete we should allow cmake to build the RLGlueExample as well.

**Comment by mgbellemare** [comment]
Looks like the only thing that's needed to fix the Makefile for Mac is to change the include in export_screen.h to

#include "environment/ale_screen.hpp"

But better would be to add full include paths to Makefile.sharedlibrary . Preference?

**Comment by mhauskn** [comment]
Okay, so I think we may be talking about different issues.

The only current issue I know with Makefile.sharedlibrary is that it doesn't set Mac's LD_LIBRARY_PATH, so I get a runtime error that libale.so is not found when I try to run the ./sharedLibraryInterfaceExample. So I then have to manually "export LD_LIBRARY_PATH=~/ArcadeLearningEnvironment/"

I take it the issue about #include "environment/ale_screen.hpp" was one you encountered with the main makefile.mac? Glad you were able to fix it, but weird that it didn't error out on my system. I think including the full path makes sense.

**Comment by mgbellemare** [comment]
The include issue was in Makefile.sharedlibrary. I added include paths (mirroring makefile.mac/unix) to fix it. Now I'm getting the libale.so runtime error. Copying/symlinking to the current directory is enough to run the example. Maybe that's an easy solution to add to the makefile?

**Comment by mhauskn** [comment]
So CMake uses the following command to make sharedLibraryInterfaceExample (and it works well enought that I don't need to set my LD_LIBRARY_PATH):

/usr/bin/c++    -Wall -Wno-multichar -Wunused -fno-rtti -fPIC -O3 -fomit-frame-pointer -framework Cocoa -Wl,-search_paths_first -Wl,-headerpad_max_install_names   CMakeFiles/sharedLibraryInterfaceExample.dir/doc/examples/sharedLibraryInterfaceExample.cpp.o  -o doc/examples/sharedLibraryInterfaceExample  -L/Users/user/projects/Arcade-Learning-Environment  -lale -lz -lsdl -lsdlmain

**Comment by mcmachado** [comment]
Just to let you know, I was able to compile my code with CMake without any
problems.
I always had to  manually "export LD_LIBRARY_PATH=~/
ArcadeLearningEnvironment/"

I'll link my previous code to the current dev version to make sure
everything is working and if I find something weird I'll let you know.

Cheers

2015-02-22 14:11 GMT-07:00 Matthew Hausknecht <notifications@github.com>:

> So CMake uses the following command to make sharedLibraryInterfaceExample
> (and it works well enought that I don't need to set my LD_LIBRARY_PATH):
>
> /usr/bin/c++ -Wall -Wno-multichar -Wunused -fno-rtti -fPIC -O3
> -fomit-frame-pointer -framework Cocoa -Wl,-search_paths_first
> -Wl,-headerpad_max_install_names
> CMakeFiles/sharedLibraryInterfaceExample.dir/doc/examples/sharedLibraryInterfaceExample.cpp.o
> -o doc/examples/sharedLibraryInterfaceExample
> -L/Users/user/projects/Arcade-Learning-Environment -lale -lz -lsdl -lsdlmain
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mgbellemare/Arcade-Learning-Environment/pull/35#issuecomment-75458502>
> .
>



-- 
Marlos Cholodovskis Machado
http://www.dcc.ufmg.br/~marlos <http://www.cs.ualberta.ca/~machado>

**Comment by mcmachado** [comment]
I want to correct myself, when I added SDL I did get an error when
compiling everything with CMake.
Is this the error you got Marc? I am going to see how to solve this, but I
want to know whether we are at the same page.

Undefined symbols for architecture x86_64:
   "_main", referenced from:
      implicit entry/start for main executable
      (maybe you meant: _SDL_main)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see
invocation)
make[2]: *** [doc/examples/sharedLibraryInterfaceExample] Error 1
make[1]: *** [CMakeFiles/sharedLibraryInterfaceExample.dir/all] Error 2
make: *** [all] Error 2

2015-02-22 15:06 GMT-07:00 Marlos C. Machado <marlos.cholodovskis@gmail.com>
:

> Just to let you know, I was able to compile my code with CMake without any
> problems.
> I always had to  manually "export LD_LIBRARY_PATH=~/
> ArcadeLearningEnvironment/"
>
> I'll link my previous code to the current dev version to make sure
> everything is working and if I find something weird I'll let you know.
>
> Cheers
>
> 2015-02-22 14:11 GMT-07:00 Matthew Hausknecht <notifications@github.com>:
>
>> So CMake uses the following command to make sharedLibraryInterfaceExample
>> (and it works well enought that I don't need to set my LD_LIBRARY_PATH):
>>
>> /usr/bin/c++ -Wall -Wno-multichar -Wunused -fno-rtti -fPIC -O3
>> -fomit-frame-pointer -framework Cocoa -Wl,-search_paths_first
>> -Wl,-headerpad_max_install_names
>> CMakeFiles/sharedLibraryInterfaceExample.dir/doc/examples/sharedLibraryInterfaceExample.cpp.o
>> -o doc/examples/sharedLibraryInterfaceExample
>> -L/Users/user/projects/Arcade-Learning-Environment -lale -lz -lsdl -lsdlmain
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mgbellemare/Arcade-Learning-Environment/pull/35#issuecomment-75458502>
>> .
>>
>
>
>
> --
> Marlos Cholodovskis Machado
> http://www.dcc.ufmg.br/~marlos <http://www.cs.ualberta.ca/~machado>
>



-- 
Marlos Cholodovskis Machado
http://www.dcc.ufmg.br/~marlos <http://www.cs.ualberta.ca/~machado>

**Comment by mgbellemare** [comment]
I haven't compiled with SDL yet, will get around to it tomorrow night 
hopefully.

**Comment by mcmachado** [comment]
Ok then.
Mine works without SDL, it doesn't, for now, with SDL. If I fix it I'll let
you know.

2015-02-22 15:19 GMT-07:00 Marc G. Bellemare <notifications@github.com>:

> I haven't compiled with SDL yet, will get around to it tomorrow night
> hopefully.
>
>
> On 22/02/2015 22:18, Marlos C. Machado wrote:
> > I want to correct myself, when I added SDL I did get an error when
> > compiling everything with CMake.
> > Is this the error you got Marc? I am going to see how to solve this, but
> I
> > want to know whether we are at the same page.
> >
> > Undefined symbols for architecture x86_64:
> > "_main", referenced from:
> > implicit entry/start for main executable
> > (maybe you meant: _SDL_main)
> > ld: symbol(s) not found for architecture x86_64
> > clang: error: linker command failed with exit code 1 (use -v to see
> > invocation)
> > make[2]: *** [doc/examples/sharedLibraryInterfaceExample] Error 1
> > make[1]: *** [CMakeFiles/sharedLibraryInterfaceExample.dir/all] Error 2
> > make: *** [all] Error 2
> >
> > 2015-02-22 15:06 GMT-07:00 Marlos C. Machado
> > <marlos.cholodovskis@gmail.com>
> > :
> >
> > > Just to let you know, I was able to compile my code with CMake
> > without any
> > > problems.
> > > I always had to manually "export LD_LIBRARY_PATH=~/
> > > ArcadeLearningEnvironment/"
> > >
> > > I'll link my previous code to the current dev version to make sure
> > > everything is working and if I find something weird I'll let you know.
> > >
> > > Cheers
> > >
> > > 2015-02-22 14:11 GMT-07:00 Matthew Hausknecht
> > <notifications@github.com>:
> > >
> > >> So CMake uses the following command to make
> > sharedLibraryInterfaceExample
> > >> (and it works well enought that I don't need to set my
> > LD_LIBRARY_PATH):
> > >>
> > >> /usr/bin/c++ -Wall -Wno-multichar -Wunused -fno-rtti -fPIC -O3
> > >> -fomit-frame-pointer -framework Cocoa -Wl,-search_paths_first
> > >> -Wl,-headerpad_max_install_names
> > >>
> >
> CMakeFiles/sharedLibraryInterfaceExample.dir/doc/examples/sharedLibraryInterfaceExample.cpp.o
> > >> -o doc/examples/sharedLibraryInterfaceExample
> > >> -L/Users/user/projects/Arcade-Learning-Environment -lale -lz -lsdl
> > -lsdlmain
> > >>
> > >> —
> > >> Reply to this email directly or view it on GitHub
> > >>
> > <
> https://github.com/mgbellemare/Arcade-Learning-Environment/pull/35#issuecomment-75458502
> >
> > >> .
> > >>
> > >
> > >
> > >
> > > --
> > > Marlos Cholodovskis Machado
> > > http://www.dcc.ufmg.br/~marlos <http://www.cs.ualberta.ca/~machado>
> > >
> >
> >
> >
> > --
> > Marlos Cholodovskis Machado
> > http://www.dcc.ufmg.br/~marlos <http://www.cs.ualberta.ca/~machado>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/mgbellemare/Arcade-Learning-Environment/pull/35#issuecomment-75466595
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mgbellemare/Arcade-Learning-Environment/pull/35#issuecomment-75466659>
> .
>



-- 
Marlos Cholodovskis Machado
http://www.dcc.ufmg.br/~marlos <http://www.cs.ualberta.ca/~machado>

**Comment by mhauskn** [comment]
One error I occasionally encounter with the CMake setup is the following:
It tries to compile the sharedLibraryExample before it finishes making
libale.so. This only happens with multithreaded make (eg make -j4) and it
only started happening since I introduced the option(BUILD_EXAMPLES "Build
Example Agents" ON). Typically I get around this error by running make a
second time. Clearly not ideal, but you might run make again to see if it
builds properly.

On Sun, Feb 22, 2015 at 4:21 PM, Marlos C. Machado <notifications@github.com

**Comment by mcmachado** [comment]
It does not fix it. I'll keep looking to see what is going on.

2015-02-22 15:26 GMT-07:00 Matthew Hausknecht <notifications@github.com>:

> One error I occasionally encounter with the CMake setup is the following:
> It tries to compile the sharedLibraryExample before it finishes making
> libale.so. This only happens with multithreaded make (eg make -j4) and it
> only started happening since I introduced the option(BUILD_EXAMPLES "Build
> Example Agents" ON). Typically I get around this error by running make a
> second time. Clearly not ideal, but you might run make again to see if it
> builds properly.
>
>
> On Sun, Feb 22, 2015 at 4:21 PM, Marlos C. Machado <
> notifications@github.com
> > wrote:
>
> > Ok then.
> > Mine works without SDL, it doesn't, for now, with SDL. If I fix it I'll
> let
> > you know.
> >
> > 2015-02-22 15:19 GMT-07:00 Marc G. Bellemare <notifications@github.com>:
> >
> >
> > > I haven't compiled with SDL yet, will get around to it tomorrow night
> > > hopefully.
> > >
> > >
> > > On 22/02/2015 22:18, Marlos C. Machado wrote:
> > > > I want to correct myself, when I added SDL I did get an error when
> > > > compiling everything with CMake.
> > > > Is this the error you got Marc? I am going to see how to solve this,
> > but
> > > I
> > > > want to know whether we are at the same page.
> > > >
> > > > Undefined symbols for architecture x86_64:
> > > > "_main", referenced from:
> > > > implicit entry/start for main executable
> > > > (maybe you meant: _SDL_main)
> > > > ld: symbol(s) not found for architecture x86_64
> > > > clang: error: linker command failed with exit code 1 (use -v to see
> > > > invocation)
> > > > make[2]: *** [doc/examples/sharedLibraryInterfaceExample] Error 1
> > > > make[1]: *** [CMakeFiles/sharedLibraryInterfaceExample.dir/all]
> Error 2
> > > > make: *** [all] Error 2
> > > >
> > > > 2015-02-22 15:06 GMT-07:00 Marlos C. Machado
> > > > <marlos.cholodovskis@gmail.com>
> > > > :
> > > >
> > > > > Just to let you know, I was able to compile my code with CMake
> > > > without any
> > > > > problems.
> > > > > I always had to manually "export LD_LIBRARY_PATH=~/
> > > > > ArcadeLearningEnvironment/"
> > > > >
> > > > > I'll link my previous code to the current dev version to make sure
> > > > > everything is working and if I find something weird I'll let you
> > know.
> > > > >
> > > > > Cheers
> > > > >
> > > > > 2015-02-22 14:11 GMT-07:00 Matthew Hausknecht
> > > > <notifications@github.com>:
> > > > >
> > > > >> So CMake uses the following command to make
> > > > sharedLibraryInterfaceExample
> > > > >> (and it works well enought that I don't need to set my
> > > > LD_LIBRARY_PATH):
> > > > >>
> > > > >> /usr/bin/c++ -Wall -Wno-multichar -Wunused -fno-rtti -fPIC -O3
> > > > >> -fomit-frame-pointer -framework Cocoa -Wl,-search_paths_first
> > > > >> -Wl,-headerpad_max_install_names
> > > > >>
> > > >
> > >
> >
> CMakeFiles/sharedLibraryInterfaceExample.dir/doc/examples/sharedLibraryInterfaceExample.cpp.o
> > > > >> -o doc/examples/sharedLibraryInterfaceExample
> > > > >> -L/Users/user/projects/Arcade-Learning-Environment -lale -lz -lsdl
> > > > -lsdlmain
> > > > >>
> > > > >> —
> > > > >> Reply to this email directly or view it on GitHub
> > > > >>
> > > > <
> > >
> >
> https://github.com/mgbellemare/Arcade-Learning-Environment/pull/35#issuecomment-75458502
> > > >
> > > > >> .
> > > > >>
> > > > >
> > > > >
> > > > >
> > > > > --
> > > > > Marlos Cholodovskis Machado
> > > > > http://www.dcc.ufmg.br/~marlos <http://www.cs.ualberta.ca/~machado
> >
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Marlos Cholodovskis Machado
> > > > http://www.dcc.ufmg.br/~marlos <http://www.cs.ualberta.ca/~machado>
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/mgbellemare/Arcade-Learning-Environment/pull/35#issuecomment-75466595
> > > >.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/mgbellemare/Arcade-Learning-Environment/pull/35#issuecomment-75466659
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Marlos Cholodovskis Machado
> > http://www.dcc.ufmg.br/~marlos <http://www.cs.ualberta.ca/~machado>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/mgbellemare/Arcade-Learning-Environment/pull/35#issuecomment-75466788
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mgbellemare/Arcade-Learning-Environment/pull/35#issuecomment-75466982>
> .
>



-- 
Marlos Cholodovskis Machado
http://www.dcc.ufmg.br/~marlos <http://www.cs.ualberta.ca/~machado>

**Comment by mcmachado** [comment]
So, I just pushed an additional line to the CMakeLists file with linking
information. Now it compiles with the SDL.

When trying to compile my own code using the new ALE, I obtained the error
Marc mentioned ('ale_screen.hpp' file not found) and even if I change the
file locally, I get runtime errors.

What I want to know is: Do we have a solution for that? Marc used the
complete path, but it is not committed. How are we going to approach this?

Cheers.

2015-02-22 15:30 GMT-07:00 Marlos C. Machado <marlos.cholodovskis@gmail.com>
:

> It does not fix it. I'll keep looking to see what is going on.
>
> 2015-02-22 15:26 GMT-07:00 Matthew Hausknecht <notifications@github.com>:
>
> One error I occasionally encounter with the CMake setup is the following:
>> It tries to compile the sharedLibraryExample before it finishes making
>> libale.so. This only happens with multithreaded make (eg make -j4) and it
>> only started happening since I introduced the option(BUILD_EXAMPLES "Build
>> Example Agents" ON). Typically I get around this error by running make a
>> second time. Clearly not ideal, but you might run make again to see if it
>> builds properly.
>>
>>
>> On Sun, Feb 22, 2015 at 4:21 PM, Marlos C. Machado <
>> notifications@github.com
>> > wrote:
>>
>> > Ok then.
>> > Mine works without SDL, it doesn't, for now, with SDL. If I fix it I'll
>> let
>> > you know.
>> >
>> > 2015-02-22 15:19 GMT-07:00 Marc G. Bellemare <notifications@github.com
>> >:
>> >
>> >
>> > > I haven't compiled with SDL yet, will get around to it tomorrow night
>> > > hopefully.
>> > >
>> > >
>> > > On 22/02/2015 22:18, Marlos C. Machado wrote:
>> > > > I want to correct myself, when I added SDL I did get an error when
>> > > > compiling everything with CMake.
>> > > > Is this the error you got Marc? I am going to see how to solve this,
>> > but
>> > > I
>> > > > want to know whether we are at the same page.
>> > > >
>> > > > Undefined symbols for architecture x86_64:
>> > > > "_main", referenced from:
>> > > > implicit entry/start for main executable
>> > > > (maybe you meant: _SDL_main)
>> > > > ld: symbol(s) not found for architecture x86_64
>> > > > clang: error: linker command failed with exit code 1 (use -v to see
>> > > > invocation)
>> > > > make[2]: *** [doc/examples/sharedLibraryInterfaceExample] Error 1
>> > > > make[1]: *** [CMakeFiles/sharedLibraryInterfaceExample.dir/all]
>> Error 2
>> > > > make: *** [all] Error 2
>> > > >
>> > > > 2015-02-22 15:06 GMT-07:00 Marlos C. Machado
>> > > > <marlos.cholodovskis@gmail.com>
>> > > > :
>> > > >
>> > > > > Just to let you know, I was able to compile my code with CMake
>> > > > without any
>> > > > > problems.
>> > > > > I always had to manually "export LD_LIBRARY_PATH=~/
>> > > > > ArcadeLearningEnvironment/"
>> > > > >
>> > > > > I'll link my previous code to the current dev version to make sure
>> > > > > everything is working and if I find something weird I'll let you
>> > know.
>> > > > >
>> > > > > Cheers
>> > > > >
>> > > > > 2015-02-22 14:11 GMT-07:00 Matthew Hausknecht
>> > > > <notifications@github.com>:
>> > > > >
>> > > > >> So CMake uses the following command to make
>> > > > sharedLibraryInterfaceExample
>> > > > >> (and it works well enought that I don't need to set my
>> > > > LD_LIBRARY_PATH):
>> > > > >>
>> > > > >> /usr/bin/c++ -Wall -Wno-multichar -Wunused -fno-rtti -fPIC -O3
>> > > > >> -fomit-frame-pointer -framework Cocoa -Wl,-search_paths_first
>> > > > >> -Wl,-headerpad_max_install_names
>> > > > >>
>> > > >
>> > >
>> >
>> CMakeFiles/sharedLibraryInterfaceExample.dir/doc/examples/sharedLibraryInterfaceExample.cpp.o
>> > > > >> -o doc/examples/sharedLibraryInterfaceExample
>> > > > >> -L/Users/user/projects/Arcade-Learning-Environment -lale -lz
>> -lsdl
>> > > > -lsdlmain
>> > > > >>
>> > > > >> —
>> > > > >> Reply to this email directly or view it on GitHub
>> > > > >>
>> > > > <
>> > >
>> >
>> https://github.com/mgbellemare/Arcade-Learning-Environment/pull/35#issuecomment-75458502
>> > > >
>> > > > >> .
>> > > > >>
>> > > > >
>> > > > >
>> > > > >
>> > > > > --
>> > > > > Marlos Cholodovskis Machado
>> > > > > http://www.dcc.ufmg.br/~marlos <
>> http://www.cs.ualberta.ca/~machado>
>> > > > >
>> > > >
>> > > >
>> > > >
>> > > > --
>> > > > Marlos Cholodovskis Machado
>> > > > http://www.dcc.ufmg.br/~marlos <http://www.cs.ualberta.ca/~machado>
>> > > >
>> > > > —
>> > > > Reply to this email directly or view it on GitHub
>> > > > <
>> > >
>> >
>> https://github.com/mgbellemare/Arcade-Learning-Environment/pull/35#issuecomment-75466595
>> > > >.
>> > >
>> > > >
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <
>> >
>> https://github.com/mgbellemare/Arcade-Learning-Environment/pull/35#issuecomment-75466659
>> > >
>> > > .
>> > >
>> >
>> >
>> >
>> > --
>> > Marlos Cholodovskis Machado
>> > http://www.dcc.ufmg.br/~marlos <http://www.cs.ualberta.ca/~machado>
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/mgbellemare/Arcade-Learning-Environment/pull/35#issuecomment-75466788
>> >
>>
>> > .
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mgbellemare/Arcade-Learning-Environment/pull/35#issuecomment-75466982>
>> .
>>
>
>
>
> --
> Marlos Cholodovskis Machado
> http://www.dcc.ufmg.br/~marlos <http://www.cs.ualberta.ca/~machado>
>



-- 
Marlos Cholodovskis Machado
http://www.dcc.ufmg.br/~marlos <http://www.cs.ualberta.ca/~machado>

**Comment by mhauskn** [comment]
Try this:

In the top of export_screen.h, change the include from #include
"ale_screen.hpp"
to #include "../environment/ale_screen.hpp"

**Comment by mcmachado** [comment]
It does work, I even tried this.
But my question is: is this what we want to do? Is this the best way to
solve the problem?

Or, more importantly, am I supposed to look for approaches that solve this
problem or has anyone else looked at it?

2015-02-23 12:13 GMT-07:00 Matthew Hausknecht <notifications@github.com>:

> Try this:
>
> In the top of export_screen.h, change the include from #include
> "ale_screen.hpp"
> to #include "../environment/ale_screen.hpp"
>
> On Mon, Feb 23, 2015 at 12:39 PM, Marlos C. Machado <
>
> notifications@github.com> wrote:
>
> > So, I just pushed an additional line to the CMakeLists file with linking
> > information. Now it compiles with the SDL.
> >
> > When trying to compile my own code using the new ALE, I obtained the
> error
> > Marc mentioned ('ale_screen.hpp' file not found) and even if I change the
> > file locally, I get runtime errors.
> >
> > What I want to know is: Do we have a solution for that? Marc used the
> > complete path, but it is not committed. How are we going to approach
> this?
> >
> > Cheers.
> >
> > 2015-02-22 15:30 GMT-07:00 Marlos C. Machado <
> > marlos.cholodovskis@gmail.com>
> > :
> >
> >
> > > It does not fix it. I'll keep looking to see what is going on.
> > >
> > > 2015-02-22 15:26 GMT-07:00 Matthew Hausknecht <
> notifications@github.com
> > >:
> > >
> > > One error I occasionally encounter with the CMake setup is the
> following:
> > >> It tries to compile the sharedLibraryExample before it finishes making
> > >> libale.so. This only happens with multithreaded make (eg make -j4) and
> > it
> > >> only started happening since I introduced the option(BUILD_EXAMPLES
> > "Build
> > >> Example Agents" ON). Typically I get around this error by running
> make a
> > >> second time. Clearly not ideal, but you might run make again to see if
> > it
> > >> builds properly.
> > >>
> > >>
> > >> On Sun, Feb 22, 2015 at 4:21 PM, Marlos C. Machado <
> > >> notifications@github.com
> > >> > wrote:
> > >>
> > >> > Ok then.
> > >> > Mine works without SDL, it doesn't, for now, with SDL. If I fix it
> > I'll
> > >> let
> > >> > you know.
> > >> >
> > >> > 2015-02-22 15:19 GMT-07:00 Marc G. Bellemare <
> > notifications@github.com
> > >> >:
> > >> >
> > >> >
> > >> > > I haven't compiled with SDL yet, will get around to it tomorrow
> > night
> > >> > > hopefully.
> > >> > >
> > >> > >
> > >> > > On 22/02/2015 22:18, Marlos C. Machado wrote:
> > >> > > > I want to correct myself, when I added SDL I did get an error
> when
> > >> > > > compiling everything with CMake.
> > >> > > > Is this the error you got Marc? I am going to see how to solve
> > this,
> > >> > but
> > >> > > I
> > >> > > > want to know whether we are at the same page.
> > >> > > >
> > >> > > > Undefined symbols for architecture x86_64:
> > >> > > > "_main", referenced from:
> > >> > > > implicit entry/start for main executable
> > >> > > > (maybe you meant: _SDL_main)
> > >> > > > ld: symbol(s) not found for architecture x86_64
> > >> > > > clang: error: linker command failed with exit code 1 (use -v to
> > see
> > >> > > > invocation)
> > >> > > > make[2]: *** [doc/examples/sharedLibraryInterfaceExample] Error
> 1
> > >> > > > make[1]: *** [CMakeFiles/sharedLibraryInterfaceExample.dir/all]
> > >> Error 2
> > >> > > > make: *** [all] Error 2
> > >> > > >
> > >> > > > 2015-02-22 15:06 GMT-07:00 Marlos C. Machado
> > >> > > > <marlos.cholodovskis@gmail.com>
> > >> > > > :
> > >> > > >
> > >> > > > > Just to let you know, I was able to compile my code with CMake
> > >> > > > without any
> > >> > > > > problems.
> > >> > > > > I always had to manually "export LD_LIBRARY_PATH=~/
> > >> > > > > ArcadeLearningEnvironment/"
> > >> > > > >
> > >> > > > > I'll link my previous code to the current dev version to make
> > sure
> > >> > > > > everything is working and if I find something weird I'll let
> you
> > >> > know.
> > >> > > > >
> > >> > > > > Cheers
> > >> > > > >
> > >> > > > > 2015-02-22 14:11 GMT-07:00 Matthew Hausknecht
> > >> > > > <notifications@github.com>:
> > >> > > > >
> > >> > > > >> So CMake uses the following command to make
> > >> > > > sharedLibraryInterfaceExample
> > >> > > > >> (and it works well enought that I don't need to set my
> > >> > > > LD_LIBRARY_PATH):
> > >> > > > >>
> > >> > > > >> /usr/bin/c++ -Wall -Wno-multichar -Wunused -fno-rtti -fPIC
> -O3
> > >> > > > >> -fomit-frame-pointer -framework Cocoa -Wl,-search_paths_first
> > >> > > > >> -Wl,-headerpad_max_install_names
> > >> > > > >>
> > >> > > >
> > >> > >
> > >> >
> > >>
> >
> CMakeFiles/sharedLibraryInterfaceExample.dir/doc/examples/sharedLibraryInterfaceExample.cpp.o
> > >> > > > >> -o doc/examples/sharedLibraryInterfaceExample
> > >> > > > >> -L/Users/user/projects/Arcade-Learning-Environment -lale -lz
> > >> -lsdl
> > >> > > > -lsdlmain
> > >> > > > >>
> > >> > > > >> —
> > >> > > > >> Reply to this email directly or view it on GitHub
> > >> > > > >>
> > >> > > > <
> > >> > >
> > >> >
> > >>
> >
> https://github.com/mgbellemare/Arcade-Learning-Environment/pull/35#issuecomment-75458502
> > >> > > >
> > >> > > > >> .
> > >> > > > >>
> > >> > > > >
> > >> > > > >
> > >> > > > >
> > >> > > > > --
> > >> > > > > Marlos Cholodovskis Machado
> > >> > > > > http://www.dcc.ufmg.br/~marlos <
> > >> http://www.cs.ualberta.ca/~machado>
> > >> > > > >
> > >> > > >
> > >> > > >
> > >> > > >
> > >> > > > --
> > >> > > > Marlos Cholodovskis Machado
> > >> > > > http://www.dcc.ufmg.br/~marlos <
> > http://www.cs.ualberta.ca/~machado>
> > >> > > >
> > >> > > > —
> > >> > > > Reply to this email directly or view it on GitHub
> > >> > > > <
> > >> > >
> > >> >
> > >>
> >
> https://github.com/mgbellemare/Arcade-Learning-Environment/pull/35#issuecomment-75466595
> > >> > > >.
> > >> > >
> > >> > > >
> > >> > >
> > >> > > —
> > >> > > Reply to this email directly or view it on GitHub
> > >> > > <
> > >> >
> > >>
> >
> https://github.com/mgbellemare/Arcade-Learning-Environment/pull/35#issuecomment-75466659
> > >> > >
> > >> > > .
> > >> > >
> > >> >
> > >> >
> > >> >
> > >> > --
> > >> > Marlos Cholodovskis Machado
> > >> > http://www.dcc.ufmg.br/~marlos <http://www.cs.ualberta.ca/~machado>
> > >> >
> > >> > —
> > >> > Reply to this email directly or view it on GitHub
> > >> > <
> > >>
> >
> https://github.com/mgbellemare/Arcade-Learning-Environment/pull/35#issuecomment-75466788
> > >> >
> > >>
> > >> > .
> > >> >
> > >>
> > >> —
> > >> Reply to this email directly or view it on GitHub
> > >> <
> >
> https://github.com/mgbellemare/Arcade-Learning-Environment/pull/35#issuecomment-75466982
> > >
> > >> .
> > >>
> > >
> > >
> > >
> > > --
> > > Marlos Cholodovskis Machado
> > > http://www.dcc.ufmg.br/~marlos <http://www.cs.ualberta.ca/~machado>
> > >
> >
> >
> >
> > --
> > Marlos Cholodovskis Machado
> > http://www.dcc.ufmg.br/~marlos <http://www.cs.ualberta.ca/~machado>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/mgbellemare/Arcade-Learning-Environment/pull/35#issuecomment-75603544
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mgbellemare/Arcade-Learning-Environment/pull/35#issuecomment-75610480>
> .
>



-- 
Marlos Cholodovskis Machado
http://www.dcc.ufmg.br/~marlos <http://www.cs.ualberta.ca/~machado>

**Comment by mhauskn** [comment]
Well, Marc added additional include paths to deal with this error: https://github.com/mgbellemare/Arcade-Learning-Environment/commit/88ee47168a5dc134a5c38098d0b2efceb49d1799

However if modifying the include statement as above fixes the problem and allows us to reduce the number of directories it's necessary to include, then I think that would be a better way to go.

**Comment by mhauskn** [comment]
Hopefully this should be fixed now by #43. Can you verify?

**Comment by mgbellemare** [comment]
Compiles out of the box for me, except sharedLibraryExample can't find libale.so. I have to ln -s build/libale.so . from the project root to get it to work. Should we be copying/symlinking libale.so to the root directory after building it?

**Comment by mhauskn** [comment]
Two questions:
1) Are you compiling with CMake? 
2) Ohhh... have you created a build directory? (I just "cmake -i ." from ALE's root directory and build inside of root.)

**Comment by mgbellemare** [comment]
Ah, yes -- I'm using a build directory. Good point.

**Comment by mhauskn** [comment]
We should change the output path of the library so it builds to the root
directory even if built inside a build directory.

**Comment by mhauskn** [comment]
I've changed the output directories so that ale and libale.so are now place
in ALE's root directory regardless of where they are built from. CMake
building should now work seamlessly from inside of a build directory.

**Pull request merged**
